export var StatusCode;
(function (StatusCode) {
    StatusCode[StatusCode["OK"] = 200] = "OK";
    StatusCode[StatusCode["CREATED"] = 201] = "CREATED";
    StatusCode[StatusCode["NO_CONTENT"] = 204] = "NO_CONTENT";
    StatusCode[StatusCode["CONFLICT"] = 205] = "CONFLICT";
    StatusCode[StatusCode["BAD_GATEWAY"] = 502] = "BAD_GATEWAY";
    StatusCode[StatusCode["BAD_REQUEST"] = 400] = "BAD_REQUEST";
    StatusCode[StatusCode["UNAUTHORIZED"] = 401] = "UNAUTHORIZED";
    StatusCode[StatusCode["ALREADY_EXISTS"] = 409] = "ALREADY_EXISTS";
    StatusCode[StatusCode["NOT_FOUND"] = 404] = "NOT_FOUND";
    StatusCode[StatusCode["INTERNAL_SERVER_ERROR"] = 500] = "INTERNAL_SERVER_ERROR";
})(StatusCode || (StatusCode = {}));
export var LogUsers;
(function (LogUsers) {
    LogUsers["USER"] = "user.service";
    LogUsers["WEBHOOK"] = "webhook.service";
    LogUsers["AUTH"] = "auth.service";
    LogUsers["PROJECT"] = "project.service";
    LogUsers["TRANSACTION"] = "transaction.service";
    LogUsers["PAYPAL"] = "paypal.service";
    LogUsers["STRIPE"] = "stripe.service";
})(LogUsers || (LogUsers = {}));
export var LogAction;
(function (LogAction) {
    LogAction["CREATE"] = "create";
    LogAction["ENCRYPT_DATA"] = "encrypt_data";
    LogAction["GET_AUTH_URL"] = "get_auth_url";
    LogAction["CREATE_PROJECT"] = "create_project";
    LogAction["FETCH_PROJECT"] = "fetch_project";
    LogAction["DELETE_PROJECT"] = "delete_project";
    LogAction["FETCH_PROJECTS"] = "fetch_projects";
    LogAction["UPLOAD_PROJECT_CODE"] = "upload_project_code";
    LogAction["CREATE_PROJECT_TOKEN"] = "create_project_token";
    LogAction["DELETE_PROJECT_TOKEN"] = "delete_project_token";
    LogAction["FETCH_PROJECT_TOKEN"] = "fetch_project_token";
    LogAction["UPDATE"] = "update";
    LogAction["DELETE"] = "delete";
    LogAction["READ"] = "read";
    LogAction["SEND"] = "send";
    LogAction["RECEIVE"] = "receive";
    LogAction["VERIFY"] = "verify";
    LogAction["SIGNUP"] = "signup";
    LogAction["ONBOARD"] = "onboard";
    LogAction["ONBOARD_BENTO"] = "onboard_bento";
    LogAction["SIGNIN"] = "signin";
    LogAction["SIGNOUT"] = "signout";
    LogAction["RESET_PASSWORD"] = "reset_password";
    LogAction["CHANGE_PASSWORD"] = "change_password";
    LogAction["FORGOT_PASSWORD"] = "forgot_password";
    LogAction["RESEND_OTP"] = "resend_otp";
    LogAction["SEND_VERIFICATION"] = "send_verification";
    LogAction["VERIFY_OTP"] = "verify_otp";
    LogAction["EMAIL_VERIFICATION"] = "email_verification";
    LogAction["PHONE_VERIFICATION"] = "phone_verification";
    LogAction["PLAID_VERIFICATION"] = "plaid_verification";
    LogAction["ERROR"] = "error";
    LogAction["CREATE_PAYPAL_ORDER"] = "create_paypal_order";
    LogAction["CAPTURE_PAYPAL_ORDER"] = "capture_paypal_order";
})(LogAction || (LogAction = {}));
export var LogStatus;
(function (LogStatus) {
    LogStatus["SUCCESS"] = "success";
    LogStatus["FAIL"] = "fail";
})(LogStatus || (LogStatus = {}));
export var LogLevel;
(function (LogLevel) {
    LogLevel["Error"] = "error";
    LogLevel["Warn"] = "warn";
    LogLevel["Info"] = "info";
    LogLevel["Verbose"] = "verbose";
    LogLevel["Debug"] = "debug";
    LogLevel["Silly"] = "silly";
})(LogLevel || (LogLevel = {}));
//# sourceMappingURL=app.types.js.map